In [82]:
import numpy as np
# ''' All data utilities are here'''
def sample_branch_data():
    branch = [[0, 4, 2], [2, 0, 4]]
    return branch

def sample_decision_tree_data():
    features = [['a', 'b'], ['b', 'a'], ['b', 'c'], ['c', 'b']]
    labels = [0, 0, 1, 1]
    return features, labels

def sample_decision_tree_test():
    features = [['a', 'b'], ['b', 'a'], ['b', 'c']]
    labels = [0, 0, 1]
    return features, labels

def sample_decision_tree_pruning():
    features = [[0, 0, 0, 0],
                [0, 0, 0, 1],
                [1, 0, 0, 0],
                [2, 1, 0, 0],
                [2, 2, 1, 0],
                [2, 2, 1, 1],
                [1, 2, 1, 1],
                [0, 1, 0, 0],
                [0, 2, 1, 0],
                [2, 1, 1, 0],
                [0, 1, 1, 1],
                [1, 1, 0, 1],
                [1, 0, 1, 0],
                [2, 1, 0, 1]
                ]
    labels = [0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0]
    validation = [[1, 0, 1, 1],
                  [1, 2, 0, 0],
                  [0, 1, 0, 1],
                  [0, 2, 0, 0],
                  [0, 1, 0, 0],
                  [0, 1, 0, 1],
                  [0, 1, 1, 1],
                  [2, 0, 0, 1],
                  [2, 1, 1, 1],
                  [2, 1, 0, 1],
                  [2, 1, 0, 0]]
    v_labels = [1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1]
    return features, labels, validation, v_labels

def most_common(lst):
    return max(set(lst), key=lst.count)


In [83]:
f = open('car.data', 'r')
white = [[int(num) for num in line.split(',')] for line in f]
white = np.asarray(white)
[N, d] = white.shape
ntr = int(np.round(N * 0.66))
ntest = N - ntr
xtrain = white[:ntr].T[:-1].T
ytrain = white[:ntr].T[-1].T
xtest = white[-ntest:].T[:-1].T
ytest = white[-ntest:].T[-1].T

for i in range(xtrain.shape[0]):
    print(xtrain[i],'-->',ytrain[i])

[0 0 2 2 0 0] --> 0
[0 0 2 2 0 1] --> 0
[0 0 2 2 0 2] --> 0
[0 0 2 2 1 0] --> 0
[0 0 2 2 1 1] --> 0
[0 0 2 2 1 2] --> 0
[0 0 2 2 2 0] --> 0
[0 0 2 2 2 1] --> 0
[0 0 2 2 2 2] --> 0
[0 0 2 4 0 0] --> 0
[0 0 2 4 0 1] --> 0
[0 0 2 4 0 2] --> 0
[0 0 2 4 1 0] --> 0
[0 0 2 4 1 1] --> 0
[0 0 2 4 1 2] --> 0
[0 0 2 4 2 0] --> 0
[0 0 2 4 2 1] --> 0
[0 0 2 4 2 2] --> 0
[0 0 2 5 0 0] --> 0
[0 0 2 5 0 1] --> 0
[0 0 2 5 0 2] --> 0
[0 0 2 5 1 0] --> 0
[0 0 2 5 1 1] --> 0
[0 0 2 5 1 2] --> 0
[0 0 2 5 2 0] --> 0
[0 0 2 5 2 1] --> 0
[0 0 2 5 2 2] --> 0
[0 0 3 2 0 0] --> 0
[0 0 3 2 0 1] --> 0
[0 0 3 2 0 2] --> 0
[0 0 3 2 1 0] --> 0
[0 0 3 2 1 1] --> 0
[0 0 3 2 1 2] --> 0
[0 0 3 2 2 0] --> 0
[0 0 3 2 2 1] --> 0
[0 0 3 2 2 2] --> 0
[0 0 3 4 0 0] --> 0
[0 0 3 4 0 1] --> 0
[0 0 3 4 0 2] --> 0
[0 0 3 4 1 0] --> 0
[0 0 3 4 1 1] --> 0
[0 0 3 4 1 2] --> 0
[0 0 3 4 2 0] --> 0
[0 0 3 4 2 1] --> 0
[0 0 3 4 2 2] --> 0
[0 0 3 5 0 0] --> 0
[0 0 3 5 0 1] --> 0
[0 0 3 5 0 2] --> 0
[0 0 3 5 1 0] --> 0
[0 0 3 5 1 1] --> 0


[2 0 4 4 1 2] --> 0
[2 0 4 4 2 0] --> 0
[2 0 4 4 2 1] --> 0
[2 0 4 4 2 2] --> 0
[2 0 4 5 0 0] --> 0
[2 0 4 5 0 1] --> 0
[2 0 4 5 0 2] --> 0
[2 0 4 5 1 0] --> 0
[2 0 4 5 1 1] --> 0
[2 0 4 5 1 2] --> 0
[2 0 4 5 2 0] --> 0
[2 0 4 5 2 1] --> 0
[2 0 4 5 2 2] --> 0
[2 0 5 2 0 0] --> 0
[2 0 5 2 0 1] --> 0
[2 0 5 2 0 2] --> 0
[2 0 5 2 1 0] --> 0
[2 0 5 2 1 1] --> 0
[2 0 5 2 1 2] --> 0
[2 0 5 2 2 0] --> 0
[2 0 5 2 2 1] --> 0
[2 0 5 2 2 2] --> 0
[2 0 5 4 0 0] --> 0
[2 0 5 4 0 1] --> 0
[2 0 5 4 0 2] --> 0
[2 0 5 4 1 0] --> 0
[2 0 5 4 1 1] --> 0
[2 0 5 4 1 2] --> 0
[2 0 5 4 2 0] --> 0
[2 0 5 4 2 1] --> 0
[2 0 5 4 2 2] --> 0
[2 0 5 5 0 0] --> 0
[2 0 5 5 0 1] --> 0
[2 0 5 5 0 2] --> 0
[2 0 5 5 1 0] --> 0
[2 0 5 5 1 1] --> 0
[2 0 5 5 1 2] --> 0
[2 0 5 5 2 0] --> 0
[2 0 5 5 2 1] --> 0
[2 0 5 5 2 2] --> 0
[2 2 2 2 0 0] --> 0
[2 2 2 2 0 1] --> 0
[2 2 2 2 0 2] --> 0
[2 2 2 2 1 0] --> 0
[2 2 2 2 1 1] --> 0
[2 2 2 2 1 2] --> 0
[2 2 2 2 2 0] --> 0
[2 2 2 2 2 1] --> 0
[2 2 2 2 2 2] --> 0
[2 2 2 4 0 0] --> 0


[1 2 3 2 0 1] --> 0
[1 2 3 2 0 2] --> 0
[1 2 3 2 1 0] --> 0
[1 2 3 2 1 1] --> 0
[1 2 3 2 1 2] --> 0
[1 2 3 2 2 0] --> 0
[1 2 3 2 2 1] --> 0
[1 2 3 2 2 2] --> 0
[1 2 3 4 0 0] --> 0
[1 2 3 4 0 1] --> 0
[1 2 3 4 0 2] --> 1
[1 2 3 4 1 0] --> 0
[1 2 3 4 1 1] --> 0
[1 2 3 4 1 2] --> 1
[1 2 3 4 2 0] --> 0
[1 2 3 4 2 1] --> 1
[1 2 3 4 2 2] --> 1
[1 2 3 5 0 0] --> 0
[1 2 3 5 0 1] --> 0
[1 2 3 5 0 2] --> 1
[1 2 3 5 1 0] --> 0
[1 2 3 5 1 1] --> 1
[1 2 3 5 1 2] --> 1
[1 2 3 5 2 0] --> 0
[1 2 3 5 2 1] --> 1
[1 2 3 5 2 2] --> 1
[1 2 4 2 0 0] --> 0
[1 2 4 2 0 1] --> 0
[1 2 4 2 0 2] --> 0
[1 2 4 2 1 0] --> 0
[1 2 4 2 1 1] --> 0
[1 2 4 2 1 2] --> 0
[1 2 4 2 2 0] --> 0
[1 2 4 2 2 1] --> 0
[1 2 4 2 2 2] --> 0
[1 2 4 4 0 0] --> 0
[1 2 4 4 0 1] --> 0
[1 2 4 4 0 2] --> 1
[1 2 4 4 1 0] --> 0
[1 2 4 4 1 1] --> 1
[1 2 4 4 1 2] --> 1
[1 2 4 4 2 0] --> 0
[1 2 4 4 2 1] --> 1
[1 2 4 4 2 2] --> 1
[1 2 4 5 0 0] --> 0
[1 2 4 5 0 1] --> 0
[1 2 4 5 0 2] --> 1
[1 2 4 5 1 0] --> 0
[1 2 4 5 1 1] --> 1
[1 2 4 5 1 2] --> 1


In [84]:
#utils.py
# TODO: Information Gain function
def Information_Gain(S, branches):
    # S: float
    # branches: List[List[int]] num_branches * num_cls
    # return: float
    arr = np.array(branches)
    net = np.sum(arr)
    total = np.sum(arr, axis = 1)
    ent = []
    for i,v in enumerate(branches):
        sum = 0
        for k in v:
            if k > 0 :
                temp = (k/total[i])*np.log2(k/total[i])
                sum = sum + temp
        ent.append(-1*sum)
    weight = 0
    for i,v in enumerate(ent):
        weight = weight + (v*(total[i])/net)
    gain = S - (weight)
    return(gain)


# TODO: implement reduced error prunning function, pruning your tree on this function
def reduced_error_prunning(decisionTree, X_test, y_test):
    # decisionTree
    # X_test: List[List[any]]
    # y_test: List
    raise NotImplementedError


# print current tree
def print_tree(decisionTree, node=None, name='branch 0', indent='', deep=0):
    if node is None:
        node = decisionTree.root_node
    print(name + '{')

    print(indent + '\tdeep: ' + str(deep))
    string = ''
    label_uniq = np.unique(node.labels).tolist()
    for label in label_uniq:
        string += str(node.labels.count(label)) + ' : '
    print(indent + '\tnum of samples for each class: ' + string[:-2])

    if node.splittable:
        print(indent + '\tsplit by dim {:d}'.format(node.dim_split))
        for idx_child, child in enumerate(node.children):
            print_tree(decisionTree, node=child, name='\t' + name + '->' + str(idx_child), indent=indent + '\t', deep=deep+1)
    else:
        print(indent + '\tclass:', node.cls_max)
    print(indent + '}')


In [85]:
#dt.py
class DecisionTree():
    def __init__(self):
        self.clf_name = "DecisionTree"
        self.root_node = None

    def train(self, features, labels):
        # features: List[List[float]], labels: List[int]
        # init
        assert (len(features) > 0)
        num_cls = np.unique(labels).size   #number of unique classes
        # build the tree
        self.root_node = TreeNode(features, labels, num_cls)
        if self.root_node.splittable:
            self.root_node.split()
        return

    def predict(self, features):
        # features: List[List[any]]
        # return List[int]
        y_pred = []
        for idx, feature in enumerate(features):
            pred = self.root_node.predict(feature)
            y_pred.append(pred)
        return y_pred


class TreeNode(object):
    def __init__(self, features, labels, num_cls):
        # features: List[List[any]], labels: List[int], num_cls: int
        self.features = features
        self.labels = labels
        self.children = []
        self.num_cls = num_cls
        # find the most common labels in current node
        count_max = 0
        for label in np.unique(labels):
            if self.labels.count(label) > count_max:
                count_max = labels.count(label)
                self.cls_max = label
                # splitable is false when all features belongs to one class
        if len(np.unique(labels)) < 2:
            self.splittable = False
        else:
            self.splittable = True
        self.dim_split = None  # the index of the feature to be split
        self.feature_uniq_split = None  # the possible unique values of the feature to be split

    #TODO: try to split current node
    def split(self):
        
        def conditional_entropy(branches):
            branches = np.array(branches)
            totals = np.sum(branches, axis=0)
            fractions = totals / np.sum(totals)
            entropy = branches / totals
            entropy = np.array([[-i * np.log2(i) if i > 0 else 0 for i in x] for x in entropy])
            entropy = np.sum(entropy, axis=0)
            entropy = np.sum(entropy * fractions)
            return entropy
        
        for idx_dim in range(len(self.features[0])):
            if not 'min_entropy' in locals():
                min_entropy = float('inf')
            xi = np.array(self.features)[:, idx_dim]
            if None in xi:
                continue
            branch_values = np.unique(xi)
            branches = np.zeros((self.num_cls, len(branch_values)))
            for i, val in enumerate(branch_values):
                y = np.array(self.labels)[np.where(xi == val)]
                for yi in y:
                    branches[yi, i] += 1
            entropy = conditional_entropy(branches)
            if entropy < min_entropy:
                min_entropy = entropy
                self.dim_split = idx_dim
                self.feature_uniq_split = branch_values.tolist()
        
        xi = np.array(self.features)[:, self.dim_split]
        x = np.array(self.features, dtype=object)
        x[:, self.dim_split] = None
        # x = np.delete(self.features, self.dim_split, axis=1)
        for val in self.feature_uniq_split:
            indexes = np.where(xi == val)
            x_new = x[indexes].tolist()
            y_new = np.array(self.labels)[indexes].tolist()
            child = TreeNode(x_new, y_new, self.num_cls)
            if np.array(x_new).size == 0 or all(v is None for v in x_new[0]):
                child.splittable = False
            self.children.append(child)
        # split the child nodes
        for child in self.children:
            if child.splittable:
                child.split()
        return

    # TODO: predict the branch or the class
    def predict(self, feature):
        # feature: List[any]
        # return: int
        if self.splittable:
            # print(feature)
            idx_child = self.feature_uniq_split.index(feature[self.dim_split])
            return self.children[idx_child].predict(feature)
        else:
            return self.cls_max


In [89]:
branch = sample_branch_data()
score = Information_Gain(0, branch)
print('Your information gain: ', score)
print('My information gain: ', -0.91829583405448956)

X_train, y_train, X_test, y_test = sample_decision_tree_pruning()

    # build the tree
dTree = DecisionTree()
dTree.train(X_train, y_train)

    # print
print('Your decision tree:')
print_tree(dTree)
print('My decision tree:')
print('branch 0{\n\tdeep: 0\n\tnum of samples for each class: 5 : 9 \n\tsplit by dim 0\n\tbranch 0->0{\n\t\tdeep: 1'
          '\n\t\tnum of samples for each class: 3 : 2 \n\t\tsplit by dim 1\n\t\tbranch 0->0->0{\n\t\t\tdeep: 2\n\t\t\t'
          'num of samples for each class: 3 \n\t\t\tclass:0\n\t\t}\n\t\tbranch 0->0->1{\n\t\t\tdeep: 2\n\t\t\tnum of '
          'samples for each class: 2 \n\t\t\tclass:1\n\t\t}\n\t}\n\tbranch 0->1{\n\t\tdeep: 1\n\t\tnum of samples for '
          'each class: 4 \n\t\tclass:1\n\t}\n\tbranch 0->2{\n\t\tdeep: 1\n\t\tnum of samples for each class: 2 : 3 '
          '\n\t\tsplit by dim 2\n\t\tbranch 0->2->0{\n\t\t\tdeep: 2\n\t\t\tnum of samples for each class: 3 \n\t\t\t'
          'class:1\n\t\t}\n\t\tbranch 0->2->1{\n\t\t\tdeep: 2\n\t\t\tnum of samples for each class: 2 \n\t\t\tclass:0'
          '\n\t\t}\n\t}\n}')


Your information gain:  -0.9182958340544896
My information gain:  -0.9182958340544896
Your decision tree:
branch 0{
	deep: 0
	num of samples for each class: 5 : 9 
	split by dim 0
	branch 0->0{
		deep: 1
		num of samples for each class: 3 : 2 
		split by dim 2
		branch 0->0->0{
			deep: 2
			num of samples for each class: 3 
			class: 0
		}
		branch 0->0->1{
			deep: 2
			num of samples for each class: 2 
			class: 1
		}
	}
	branch 0->1{
		deep: 1
		num of samples for each class: 4 
		class: 1
	}
	branch 0->2{
		deep: 1
		num of samples for each class: 2 : 3 
		split by dim 3
		branch 0->2->0{
			deep: 2
			num of samples for each class: 3 
			class: 1
		}
		branch 0->2->1{
			deep: 2
			num of samples for each class: 2 
			class: 0
		}
	}
}
My decision tree:
branch 0{
	deep: 0
	num of samples for each class: 5 : 9 
	split by dim 0
	branch 0->0{
		deep: 1
		num of samples for each class: 3 : 2 
		split by dim 1
		branch 0->0->0{
			deep: 2
			num of samples for each class: 3 
			class: